name = "FastChebInterp"
uuid = "cf66c380-9a80-432c-aff8-4f9c79c0bdde"
version = "1.2.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"

[compat]
ChainRulesCore = "1"
ChainRulesTestUtils = "1"
FFTW = "1.0"
StaticArrays = "0.12, 1.0"
julia = "1.3"

[extras]
ChainRulesTestUtils = "cdddcdb0-9152-4a09-a978-84456f9df70a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ChainRulesTestUtils", "Random", "Test"]
